CREATE DATABASE lv_safety_verification;
use lv_safety_verification;


-----------> CUSTOMER DETAILS <----------
		
			CREATE TABLE customer_details_table(
				    RISK_ID INT AUTO_INCREMENT,
				    USER_NAME VARCHAR(255),
				    ORGANISATION_NAME VARCHAR(255),
				    ADDRESS VARCHAR(255),
				    PROJECT_NAME VARCHAR(255),
				    PROJECT_DESC VARCHAR(500),
				    CONTACT_NO VARCHAR(255),
				    CONTACT_DETAILS VARCHAR(255),
				    PREPARED_BY VARCHAR(255),
				    VERIFIED_BY VARCHAR(255),
				    CREATED_BY VARCHAR(255),
				    CREATED_DATE datetime,
			        UPDATED_BY VARCHAR(255),
			        UPDATED_DATE datetime,
			        CONSTRAINT PK_RISK_ID  PRIMARY KEY(RISK_ID)
			        )
			        
			        
-----------> STRUCTURE DETAILS <----------	

			       CREATE TABLE structure_characterisics_table(
				    STRUCTURE_CHARACTERISTIC_ID INT AUTO_INCREMENT,
				    USER_NAME VARCHAR(255),
				    RISK_ID INT,
				    LOCATION VARCHAR(255),
				    OTHER_LOCATION VARCHAR(255),
				    GROUND_FLASH_DENSITY VARCHAR(255),
				    TYPE_OF_BUILDING VARCHAR(255),
				    ST_SCREENING_EFFECTIVENESS VARCHAR(255),
				    IN_SCREENING_EFFECTIVENESS VARCHAR(255),
				    PROTRUSION_LENGHT VARCHAR(255),
				    PROTRUSION_WIDTH VARCHAR(255),
				    PROTRUSION_HEIGHT VARCHAR(255),
				    HEIGHEST_ROOF_PROTRUSION VARCHAR(255),
				    COLL_AREA_STRUCTURE VARCHAR(255),
				    COLL_AREA_STRUC_PROTRUSION VARCHAR(255),
				    COLL_AREA_NEAR_STRUC VARCHAR(255),
				    HEIGHT_NEARBY_STRUCTURE VARCHAR(255),
				    TELEPHONE_SERVICE_LINE VARCHAR(255),
				    ENVIRONMENT VARCHAR(255),
				    NO_OF_DANG_EVENT_ON_STRUCTURE VARCHAR(255),
				    PROTECTION_PART_BUILDING VARCHAR(255),
				    PROTECTION_LENGHT VARCHAR(255),
				    PROTECTION_WIDTH VARCHAR(255),
				    PROTECTION_HEIGHT VARCHAR(255),
				    PRO_COLL_AREA VARCHAR(255),
				    ADJACENT_BUILDING VARCHAR(255),
				    ADJ_LENGTH VARCHAR(255),
				    ADJ_WIDTH VARCHAR(255),
				    ADJ_HEIGHT VARCHAR(255),
				    COLL_AREA_ADJ_STRUC VARCHAR(255),
				    NO_OF_DANG_EVENT_ON_ADJ_STRUC VARCHAR(255),
				    NO_OF_PEOPLE_BUILDING VARCHAR(255),
				    NO_OF_PEOPLE_ZONE VARCHAR(255),
				    DAY_PEOP_PRESENT__BUILDING VARCHAR(255),
				    YEAR_PEOP_PRESENT__BUILDING VARCHAR(255),
			        CREATED_BY VARCHAR(255),
				    CREATED_DATE datetime,
			        UPDATED_BY VARCHAR(255),
			        UPDATED_DATE datetime,
					CONSTRAINT PK_STRUCTURE_CHARACTERISTIC_ID  PRIMARY KEY(STRUCTURE_CHARACTERISTIC_ID)
					);
					
					
			CREATE TABLE structure_attributes_table(
				    STRUCTURE_ATTRIBUTES_ID INT AUTO_INCREMENT,
					
				    STRUCTURE_CHARACTERISTIC_ID INT,
				    HL_HAZARD_CLASSIFICATION VARCHAR(255),
				    HL_PHYSICAL_DAMAGE VARCHAR(255),
				    HL_FAILURE_INTERNAL_SYSTEM VARCHAR(255),
				    HL_INJURY_ELECTRIC_SHOCK VARCHAR(255),
				    HL_PHYSICAL_DAMAGE_L1 VARCHAR(255),
				    
				    SP_PHYSICAL_DAMAGE VARCHAR(255),
				    SP_FAILURE_INTERNAL_SYSTEM VARCHAR(255),
				     
				    CH_PHYSICAL_DAMAGE VARCHAR(255),
				    
				    EL_PHYSICAL_DAMAGE VARCHAR(255),
				    EL_FAILURE_INTERNAL_SYSTEM VARCHAR(255),
				    EL_INJURY_ELECTRIC_SHOCK VARCHAR(255),
				    
				    PROTEC_CLASS_LPS VARCHAR(255),
				    PROTEC_CLASS_SPD VARCHAR(255),
               
					CONSTRAINT PK_STRUCTURE_ATTRIBUTES_ID PRIMARY KEY(STRUCTURE_ATTRIBUTES_ID),
					CONSTRAINT FK_STRUCTURE_CHARACTERISTIC_ID FOREIGN KEY (STRUCTURE_CHARACTERISTIC_ID) REFERENCES structure_characterisics_table(STRUCTURE_CHARACTERISTIC_ID) ON DELETE CASCADE    
					);
					